"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['bomb.py',
 'bomber_constants.py',
 'bombermap.py',
 'drawstuff.py',
 'explosion.py',
 'main.py',
 'menu.py',
 'player.py',
 'powerup.py',
 'py2applet.py',
 'setup.py',
 'img',
 'fonts',
 'map.txt']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/pierre/Dropbox/programs/projects/bomberman/img/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
